// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// BlogColumns holds the columns for the "blog" table.
	BlogColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint64, Increment: true},
		{Name: "title", Type: field.TypeString},
		{Name: "address", Type: field.TypeString},
		{Name: "user_id", Type: field.TypeUint64},
		{Name: "ctime", Type: field.TypeInt64},
		{Name: "desc", Type: field.TypeString},
	}
	// BlogTable holds the schema information for the "blog" table.
	BlogTable = &schema.Table{
		Name:       "blog",
		Columns:    BlogColumns,
		PrimaryKey: []*schema.Column{BlogColumns[0]},
	}
	// TagsColumns holds the columns for the "tags" table.
	TagsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint64, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "user_id", Type: field.TypeUint64},
		{Name: "article_id", Type: field.TypeUint64},
	}
	// TagsTable holds the schema information for the "tags" table.
	TagsTable = &schema.Table{
		Name:       "tags",
		Columns:    TagsColumns,
		PrimaryKey: []*schema.Column{TagsColumns[0]},
	}
	// UserColumns holds the columns for the "user" table.
	UserColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint64, Increment: true},
		{Name: "account", Type: field.TypeString},
		{Name: "password", Type: field.TypeString},
		{Name: "desc", Type: field.TypeString},
		{Name: "location", Type: field.TypeString},
	}
	// UserTable holds the schema information for the "user" table.
	UserTable = &schema.Table{
		Name:       "user",
		Columns:    UserColumns,
		PrimaryKey: []*schema.Column{UserColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		BlogTable,
		TagsTable,
		UserTable,
	}
)

func init() {
	BlogTable.Annotation = &entsql.Annotation{
		Table: "blog",
	}
	UserTable.Annotation = &entsql.Annotation{
		Table: "user",
	}
}
