// Code generated by ent, DO NOT EDIT.

package ent

import (
	"backend/internal/ent/blog"
	"backend/internal/ent/predicate"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// BlogUpdate is the builder for updating Blog entities.
type BlogUpdate struct {
	config
	hooks     []Hook
	mutation  *BlogMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the BlogUpdate builder.
func (bu *BlogUpdate) Where(ps ...predicate.Blog) *BlogUpdate {
	bu.mutation.Where(ps...)
	return bu
}

// SetTitle sets the "title" field.
func (bu *BlogUpdate) SetTitle(s string) *BlogUpdate {
	bu.mutation.SetTitle(s)
	return bu
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (bu *BlogUpdate) SetNillableTitle(s *string) *BlogUpdate {
	if s != nil {
		bu.SetTitle(*s)
	}
	return bu
}

// SetAddress sets the "address" field.
func (bu *BlogUpdate) SetAddress(s string) *BlogUpdate {
	bu.mutation.SetAddress(s)
	return bu
}

// SetNillableAddress sets the "address" field if the given value is not nil.
func (bu *BlogUpdate) SetNillableAddress(s *string) *BlogUpdate {
	if s != nil {
		bu.SetAddress(*s)
	}
	return bu
}

// SetUserID sets the "user_id" field.
func (bu *BlogUpdate) SetUserID(u uint64) *BlogUpdate {
	bu.mutation.ResetUserID()
	bu.mutation.SetUserID(u)
	return bu
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (bu *BlogUpdate) SetNillableUserID(u *uint64) *BlogUpdate {
	if u != nil {
		bu.SetUserID(*u)
	}
	return bu
}

// AddUserID adds u to the "user_id" field.
func (bu *BlogUpdate) AddUserID(u int64) *BlogUpdate {
	bu.mutation.AddUserID(u)
	return bu
}

// SetCtime sets the "ctime" field.
func (bu *BlogUpdate) SetCtime(i int64) *BlogUpdate {
	bu.mutation.ResetCtime()
	bu.mutation.SetCtime(i)
	return bu
}

// SetNillableCtime sets the "ctime" field if the given value is not nil.
func (bu *BlogUpdate) SetNillableCtime(i *int64) *BlogUpdate {
	if i != nil {
		bu.SetCtime(*i)
	}
	return bu
}

// AddCtime adds i to the "ctime" field.
func (bu *BlogUpdate) AddCtime(i int64) *BlogUpdate {
	bu.mutation.AddCtime(i)
	return bu
}

// SetDesc sets the "desc" field.
func (bu *BlogUpdate) SetDesc(s string) *BlogUpdate {
	bu.mutation.SetDesc(s)
	return bu
}

// SetNillableDesc sets the "desc" field if the given value is not nil.
func (bu *BlogUpdate) SetNillableDesc(s *string) *BlogUpdate {
	if s != nil {
		bu.SetDesc(*s)
	}
	return bu
}

// Mutation returns the BlogMutation object of the builder.
func (bu *BlogUpdate) Mutation() *BlogMutation {
	return bu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (bu *BlogUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, bu.sqlSave, bu.mutation, bu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (bu *BlogUpdate) SaveX(ctx context.Context) int {
	affected, err := bu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (bu *BlogUpdate) Exec(ctx context.Context) error {
	_, err := bu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (bu *BlogUpdate) ExecX(ctx context.Context) {
	if err := bu.Exec(ctx); err != nil {
		panic(err)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (bu *BlogUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *BlogUpdate {
	bu.modifiers = append(bu.modifiers, modifiers...)
	return bu
}

func (bu *BlogUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(blog.Table, blog.Columns, sqlgraph.NewFieldSpec(blog.FieldID, field.TypeUint64))
	if ps := bu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := bu.mutation.Title(); ok {
		_spec.SetField(blog.FieldTitle, field.TypeString, value)
	}
	if value, ok := bu.mutation.Address(); ok {
		_spec.SetField(blog.FieldAddress, field.TypeString, value)
	}
	if value, ok := bu.mutation.UserID(); ok {
		_spec.SetField(blog.FieldUserID, field.TypeUint64, value)
	}
	if value, ok := bu.mutation.AddedUserID(); ok {
		_spec.AddField(blog.FieldUserID, field.TypeUint64, value)
	}
	if value, ok := bu.mutation.Ctime(); ok {
		_spec.SetField(blog.FieldCtime, field.TypeInt64, value)
	}
	if value, ok := bu.mutation.AddedCtime(); ok {
		_spec.AddField(blog.FieldCtime, field.TypeInt64, value)
	}
	if value, ok := bu.mutation.Desc(); ok {
		_spec.SetField(blog.FieldDesc, field.TypeString, value)
	}
	_spec.AddModifiers(bu.modifiers...)
	if n, err = sqlgraph.UpdateNodes(ctx, bu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{blog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	bu.mutation.done = true
	return n, nil
}

// BlogUpdateOne is the builder for updating a single Blog entity.
type BlogUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *BlogMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetTitle sets the "title" field.
func (buo *BlogUpdateOne) SetTitle(s string) *BlogUpdateOne {
	buo.mutation.SetTitle(s)
	return buo
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (buo *BlogUpdateOne) SetNillableTitle(s *string) *BlogUpdateOne {
	if s != nil {
		buo.SetTitle(*s)
	}
	return buo
}

// SetAddress sets the "address" field.
func (buo *BlogUpdateOne) SetAddress(s string) *BlogUpdateOne {
	buo.mutation.SetAddress(s)
	return buo
}

// SetNillableAddress sets the "address" field if the given value is not nil.
func (buo *BlogUpdateOne) SetNillableAddress(s *string) *BlogUpdateOne {
	if s != nil {
		buo.SetAddress(*s)
	}
	return buo
}

// SetUserID sets the "user_id" field.
func (buo *BlogUpdateOne) SetUserID(u uint64) *BlogUpdateOne {
	buo.mutation.ResetUserID()
	buo.mutation.SetUserID(u)
	return buo
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (buo *BlogUpdateOne) SetNillableUserID(u *uint64) *BlogUpdateOne {
	if u != nil {
		buo.SetUserID(*u)
	}
	return buo
}

// AddUserID adds u to the "user_id" field.
func (buo *BlogUpdateOne) AddUserID(u int64) *BlogUpdateOne {
	buo.mutation.AddUserID(u)
	return buo
}

// SetCtime sets the "ctime" field.
func (buo *BlogUpdateOne) SetCtime(i int64) *BlogUpdateOne {
	buo.mutation.ResetCtime()
	buo.mutation.SetCtime(i)
	return buo
}

// SetNillableCtime sets the "ctime" field if the given value is not nil.
func (buo *BlogUpdateOne) SetNillableCtime(i *int64) *BlogUpdateOne {
	if i != nil {
		buo.SetCtime(*i)
	}
	return buo
}

// AddCtime adds i to the "ctime" field.
func (buo *BlogUpdateOne) AddCtime(i int64) *BlogUpdateOne {
	buo.mutation.AddCtime(i)
	return buo
}

// SetDesc sets the "desc" field.
func (buo *BlogUpdateOne) SetDesc(s string) *BlogUpdateOne {
	buo.mutation.SetDesc(s)
	return buo
}

// SetNillableDesc sets the "desc" field if the given value is not nil.
func (buo *BlogUpdateOne) SetNillableDesc(s *string) *BlogUpdateOne {
	if s != nil {
		buo.SetDesc(*s)
	}
	return buo
}

// Mutation returns the BlogMutation object of the builder.
func (buo *BlogUpdateOne) Mutation() *BlogMutation {
	return buo.mutation
}

// Where appends a list predicates to the BlogUpdate builder.
func (buo *BlogUpdateOne) Where(ps ...predicate.Blog) *BlogUpdateOne {
	buo.mutation.Where(ps...)
	return buo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (buo *BlogUpdateOne) Select(field string, fields ...string) *BlogUpdateOne {
	buo.fields = append([]string{field}, fields...)
	return buo
}

// Save executes the query and returns the updated Blog entity.
func (buo *BlogUpdateOne) Save(ctx context.Context) (*Blog, error) {
	return withHooks(ctx, buo.sqlSave, buo.mutation, buo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (buo *BlogUpdateOne) SaveX(ctx context.Context) *Blog {
	node, err := buo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (buo *BlogUpdateOne) Exec(ctx context.Context) error {
	_, err := buo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (buo *BlogUpdateOne) ExecX(ctx context.Context) {
	if err := buo.Exec(ctx); err != nil {
		panic(err)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (buo *BlogUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *BlogUpdateOne {
	buo.modifiers = append(buo.modifiers, modifiers...)
	return buo
}

func (buo *BlogUpdateOne) sqlSave(ctx context.Context) (_node *Blog, err error) {
	_spec := sqlgraph.NewUpdateSpec(blog.Table, blog.Columns, sqlgraph.NewFieldSpec(blog.FieldID, field.TypeUint64))
	id, ok := buo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Blog.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := buo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, blog.FieldID)
		for _, f := range fields {
			if !blog.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != blog.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := buo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := buo.mutation.Title(); ok {
		_spec.SetField(blog.FieldTitle, field.TypeString, value)
	}
	if value, ok := buo.mutation.Address(); ok {
		_spec.SetField(blog.FieldAddress, field.TypeString, value)
	}
	if value, ok := buo.mutation.UserID(); ok {
		_spec.SetField(blog.FieldUserID, field.TypeUint64, value)
	}
	if value, ok := buo.mutation.AddedUserID(); ok {
		_spec.AddField(blog.FieldUserID, field.TypeUint64, value)
	}
	if value, ok := buo.mutation.Ctime(); ok {
		_spec.SetField(blog.FieldCtime, field.TypeInt64, value)
	}
	if value, ok := buo.mutation.AddedCtime(); ok {
		_spec.AddField(blog.FieldCtime, field.TypeInt64, value)
	}
	if value, ok := buo.mutation.Desc(); ok {
		_spec.SetField(blog.FieldDesc, field.TypeString, value)
	}
	_spec.AddModifiers(buo.modifiers...)
	_node = &Blog{config: buo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, buo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{blog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	buo.mutation.done = true
	return _node, nil
}
