// Code generated by ent, DO NOT EDIT.

package ent

import (
	"backend/internal/ent/tags"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TagsCreate is the builder for creating a Tags entity.
type TagsCreate struct {
	config
	mutation *TagsMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (tc *TagsCreate) SetName(s string) *TagsCreate {
	tc.mutation.SetName(s)
	return tc
}

// SetUserID sets the "user_id" field.
func (tc *TagsCreate) SetUserID(u uint64) *TagsCreate {
	tc.mutation.SetUserID(u)
	return tc
}

// SetArticleID sets the "article_id" field.
func (tc *TagsCreate) SetArticleID(u uint64) *TagsCreate {
	tc.mutation.SetArticleID(u)
	return tc
}

// SetID sets the "id" field.
func (tc *TagsCreate) SetID(u uint64) *TagsCreate {
	tc.mutation.SetID(u)
	return tc
}

// Mutation returns the TagsMutation object of the builder.
func (tc *TagsCreate) Mutation() *TagsMutation {
	return tc.mutation
}

// Save creates the Tags in the database.
func (tc *TagsCreate) Save(ctx context.Context) (*Tags, error) {
	return withHooks(ctx, tc.sqlSave, tc.mutation, tc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (tc *TagsCreate) SaveX(ctx context.Context) *Tags {
	v, err := tc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (tc *TagsCreate) Exec(ctx context.Context) error {
	_, err := tc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tc *TagsCreate) ExecX(ctx context.Context) {
	if err := tc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (tc *TagsCreate) check() error {
	if _, ok := tc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Tags.name"`)}
	}
	if _, ok := tc.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "Tags.user_id"`)}
	}
	if _, ok := tc.mutation.ArticleID(); !ok {
		return &ValidationError{Name: "article_id", err: errors.New(`ent: missing required field "Tags.article_id"`)}
	}
	return nil
}

func (tc *TagsCreate) sqlSave(ctx context.Context) (*Tags, error) {
	if err := tc.check(); err != nil {
		return nil, err
	}
	_node, _spec := tc.createSpec()
	if err := sqlgraph.CreateNode(ctx, tc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = uint64(id)
	}
	tc.mutation.id = &_node.ID
	tc.mutation.done = true
	return _node, nil
}

func (tc *TagsCreate) createSpec() (*Tags, *sqlgraph.CreateSpec) {
	var (
		_node = &Tags{config: tc.config}
		_spec = sqlgraph.NewCreateSpec(tags.Table, sqlgraph.NewFieldSpec(tags.FieldID, field.TypeUint64))
	)
	if id, ok := tc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := tc.mutation.Name(); ok {
		_spec.SetField(tags.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := tc.mutation.UserID(); ok {
		_spec.SetField(tags.FieldUserID, field.TypeUint64, value)
		_node.UserID = value
	}
	if value, ok := tc.mutation.ArticleID(); ok {
		_spec.SetField(tags.FieldArticleID, field.TypeUint64, value)
		_node.ArticleID = value
	}
	return _node, _spec
}

// TagsCreateBulk is the builder for creating many Tags entities in bulk.
type TagsCreateBulk struct {
	config
	err      error
	builders []*TagsCreate
}

// Save creates the Tags entities in the database.
func (tcb *TagsCreateBulk) Save(ctx context.Context) ([]*Tags, error) {
	if tcb.err != nil {
		return nil, tcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(tcb.builders))
	nodes := make([]*Tags, len(tcb.builders))
	mutators := make([]Mutator, len(tcb.builders))
	for i := range tcb.builders {
		func(i int, root context.Context) {
			builder := tcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TagsMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, tcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, tcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = uint64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, tcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (tcb *TagsCreateBulk) SaveX(ctx context.Context) []*Tags {
	v, err := tcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (tcb *TagsCreateBulk) Exec(ctx context.Context) error {
	_, err := tcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tcb *TagsCreateBulk) ExecX(ctx context.Context) {
	if err := tcb.Exec(ctx); err != nil {
		panic(err)
	}
}
